# This is a basic workflow to help you get started with Actions

name: BarCode-cpp-Sitemap-Generator

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: true  # Fetch Hugo themes
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install sitemap-generator
        run:  npm install -g sitemap-generator-cli
      - name: Generate Sitemap
        run:  npx sitemap-generator-cli https://apireference.aspose.com/barcode/cpp -f aspose-barcode-cpp-sitemap.xml -v
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "muhammad.muqarrab@aspose.com"
          git config --local user.name "muqarrab-aspose"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.REPO_TOKEN }}
